In [4]:
import pandas as pd

In [3]:
xlsx_file = "dados/Consolidado - 2010 - 2019 - EB Privado.xlsx"

df = pd.read_excel(xlsx_file, engine="openpyxl")

# Salvar como Parquet
arquivo_csv = 'dados/EBMATRICULAS.csv'
df.to_csv(arquivo_csv, index=False)

print(f"Arquivo convertido para Csv: {arquivo_csv}")

Arquivo convertido para Csv: dados/EBMATRICULAS.csv

In [5]:
df =pd.read_csv('DADOS/CursosDB.csv')

df.head()

C:\Users\VenancioFreitas\AppData\Local\Temp\ipykernel_8600\484154459.py:1: DtypeWarning: Columns (0,1,6,9,12,14,17,20,21,22,23,24,25,26,27,28,30,32,34,35,36,37,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df =pd.read_csv('DADOS/CursosDB.csv')

,Código Cidade e IES,Código IES,Nome IES,Nome da IES Ajustado,Grupo Ajustado,Grupo Ajustado (Cias. Abertas),Código da Categoria Administrativa,Categoria Administrativa,Categoria Adm Ajustada,Código da Organização Acadêmica,...,Grau Acadêmico,Código da Modalidade de Ensino,Modalidade de Ensino,Código do Nível Acadêmico,Nível Acadêmico,Unnamed: 34,Matriculados,Concluintes,Ingressantes,Ano Base
0,Código Cidade e IES,Código IES,Nome IES,Nome da IES Ajustado,Grupo,Grupo Ajustado (Cias. Abertas),Código da Categoria Administrativa,Categoria Administrativa,Categoria Adm Ajustada,Código da Organização Acadêmica,...,Grau Acadêmico,Código da Modalidade de Ensino,Modalidade de Ensino,Código do Nível Acadêmico,Nível Acadêmico,xxx,Matriculados,Concluintes,Ingressantes,Ano Base
1,2103703UNIVERSIDADE ESTADUAL DO MARANHÃO,568,UNIVERSIDADE ESTADUAL DO MARANHÃO,Universidade Estadual Do Maranhão,UNIVERSIDADE ESTADUAL DO MARANHÃO,0,2,Pública Estadual,Ensino Público,1,...,Licenciatura,1,Presencial,1,Graduação,NaN,27,0,27,2010
2,3552106FACULDADE XV DE AGOSTO,1725,FACULDADE XV DE AGOSTO,Faculdade Xv De Agosto,Faculdade Xv De Agosto,-,4,Privada com fins lucrativos,Ensino Privado,3,...,Bacharelado,1,Presencial,1,Graduação,NaN,33,33,0,2010
3,2606200FACULDADE DE FORMAÇÃO DE PROFESSORES DE...,702,FACULDADE DE FORMAÇÃO DE PROFESSORES DE GOIANA,Faculdade De Formação De Professores De Goiana,FACULDADE DE CIÊNCIAS E TECNOLOGIA PROFESSOR ...,0,3,Pública Municipal,Ensino Público,3,...,Licenciatura,1,Presencial,1,Graduação,NaN,163,0,68,2010
4,2312908UNIVERSIDADE ESTADUAL DO VALE DO ACARAÚ,95,UNIVERSIDADE ESTADUAL DO VALE DO ACARAÚ,Universidade Estadual Do Vale Do Acaraú,UNIVERSIDADE ESTADUAL DO VALE DO ACARAÚ,0,2,Pública Estadual,Ensino Público,1,...,Bacharelado,1,Presencial,1,Graduação,NaN,141,0,160,2010